"""Generate a comprehensive char->Jyutping map for the web client.

Iterates the CJK Unified Ideographs block, takes the most-common single reading
per character from pycantonese, and writes docs/js/jyutping-data.js.

Run (inside the venv with pycantonese installed):
    python scripts/gen_jyutping_data.py
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")
import pycantonese  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "docs" / "js" / "jyutping-data.js"

START, END = 0x4E00, 0x9FFF  # CJK Unified Ideographs


def first_syllable(jp: str) -> str:
    for i, ch in enumerate(jp):
        if ch.isdigit():
            return jp[: i + 1]
    return jp


def build() -> dict[str, str]:
    table: dict[str, str] = {}
    for code in range(START, END + 1):
        ch = chr(code)
        try:
            pairs = pycantonese.characters_to_jyutping(ch)
        except Exception:
            continue
        if pairs and pairs[0][1]:
            table[ch] = first_syllable(pairs[0][1])
    return table


def add_simplified(table: dict[str, str]) -> int:
    """Map simplified characters to their traditional reading via hanziconv."""
    from hanziconv import HanziConv

    added = 0
    for code in range(START, END + 1):
        ch = chr(code)
        if ch in table:
            continue
        trad = HanziConv.toTraditional(ch)
        if trad != ch and trad in table:
            table[ch] = table[trad]
            added += 1
    return added


def main() -> None:
    table = build()
    simplified = add_simplified(table)
    payload = json.dumps(table, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    header = (
        "// AUTO-GENERATED by scripts/gen_jyutping_data.py — do not edit by hand.\n"
        "// Source: pycantonese (rime-cantonese / CC-Canto) + hanziconv simplified fallback.\n"
        f"// {len(table)} characters covered ({simplified} via simplified->traditional).\n"
        "export const BUNDLED = "
    )
    OUT.write_text(header + payload + ";\n", encoding="utf-8")
    print(f"wrote {len(table)} characters ({simplified} simplified) to {OUT}")


if __name__ == "__main__":
    main()
